IP: "10.43.0.146"
port: 6789
HOME: [3.14, 2.857, 1.362, 0.0]
GRAVITY_VECTOR: [0.0, 0.0, -9.81]
MAX_CURRENT_mA: 2000.0
MAX_CURRENT_mA_GO_HOME: 1000.0
MAX_MANIPULABILITY: 7.0
MAX_RATIO_FORCE_ELLIPSOID: 0.15
MAX_SPEED_TELEOP: 0.25
LOOP_FREQUENCY: 250.0
tool_link: "cp_probe_3"
